### ISSUE TITLE
Issues with --parallel

### ISSUE THREAD

**Issue by samueltootle** [Sbozzolo/motionpicture#3]
When attempting to use mopi with the kuibit grid_var movie file using the following command:
```bash
mopi grid_var -o kuiout/ -v --parallel --datadir <simdir> \
--variable H --logscale --absolute --vmin -10 --vmax -1 --colorbar --resolution 300 -x0 -50 -50 -x1 50 50
```
Which eventually results in the following error:

> GVFS-WARNING **: 06:17:27.075: Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.Daemon: Timeout was reached (g-io-error-quark, 24)

If I remove the `--parallel` option, the movie is created as expected.  Any ideas?

I'm running on popos 21.10 and I've updated to mopi 0.3 and kuibit 1.3.5.
```bash
# uname - a
Linux pop-os 5.17.5-76051705-generic #202204271406~1653440576~21.10~6277a18 SMP PREEMPT Wed May 25 01 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by irrationalnumbers** [comment]
I've since upgraded to PopOS 22.04 and this is no longer present.  I wasn't able to resolve this without the upgrade unfortunately.
